# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-27 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20180118_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='surname',
        ),
    ]
