# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20180127_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_time',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
