# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_customer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_ekb',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='check_russia',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
