# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20180128_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_ekb',
            field=models.BooleanField(default=False),
        ),
    ]
