# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_new_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_items',
            field=models.BooleanField(default=False),
        ),
    ]
