# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_hit_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likeTrue',
            field=models.BooleanField(default=True),
        ),
    ]
