# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180120_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likeTrue',
            field=models.BooleanField(default=True),
        ),
    ]
