# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likeTrue',
        ),
    ]
