# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180121_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Похожий товар',
                'verbose_name_plural': 'Похожие товары',
            },
        ),
    ]
