# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_similarproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similarproducts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SimilarProducts'),
        ),
    ]
