# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_similarproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('comments', models.CharField(max_length=528)),
            ],
            options={
                'verbose_name': 'ProductComment',
                'verbose_name_plural': 'ProductComments',
            },
        ),
    ]
