# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180224_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomments',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
