# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_productcomments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomments',
            name='published_date',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
